global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'lina'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['${TARGET_HOST}:9090']

  # Ledger service
  - job_name: 'ledger'
    static_configs:
      - targets: ['${TARGET_HOST}:9460']

  #  Consumption service
  - job_name: 'consumption'
    static_configs:
      - targets: ['${TARGET_HOST}:9465']

  # Device service
  - job_name: 'device'
    static_configs:
      - targets: ['${TARGET_HOST}:9466']

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['${TARGET_HOST}:9461']

  # Cadvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['${TARGET_HOST}:9462']

  # Node exporter
  - job_name: 'node'
    static_configs:
      - targets: ['${TARGET_HOST}:9463']