{
 "title": "LINA Monitoring",
 "time": { "from": "2025-12-16T10:48:00.193Z", "to": "2025-12-16T11:18:00.193Z" },
 "panels": [
  { "title": "Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk write throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_fs_writes_bytes_total{name!=\"\", name!~\".*_exporter.*\"}[30s])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk read throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_fs_reads_bytes_total{name!=\"\", name!~\".*_exporter.*\"}[30s])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name!=\"\", name!~\".*_exporter.*\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network receive throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_network_receive_bytes_total{name!=\"\", name!~\".*_exporter.*\"}[30s])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network transmit throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_network_transmit_bytes_total{name!=\"\", name!~\".*_exporter.*\"}[30s])\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{name!=\"\", name!~\".*_exporter.*\"}[1m])) by (instance, name)) / on(instance) group_left() (sum by (instance) (machine_cpu_cores)) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Virtual Users over time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "devices" } },
   "targets": [
    { "expr": "max_over_time(k6_vus[15s])", "legendFormat": "Devices" }
   ]
  },
  {
   "title": "Ledger commits latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ledger_tx_commit_seconds_bucket{outcome=\"ok\"}[1m])) by (le, operation))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumption Recorded per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "debits/s" } },
   "targets": [
    {
     "expr": "sum(rate(consumption_events_total[30s]))",
     "legendFormat": "Devices"
    }
   ]
  },
  {
   "title": "p99 handler latency by stream/op",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ledger_stream_handler_seconds_bucket{outcome=\"ok\"}[1m])) by (le, stream, operation, mode))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 message age (queue delay signal):",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ledger_stream_message_age_seconds_bucket[1m])) by (le, stream, operation, mode))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authorization Debits per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "debits/s" } },
   "targets": [
    {
     "expr": "sum(rate(ledger_authorizations_total{operation=\"debited\"}[30s]))",
     "legendFormat": "Devices"
    }
   ]
  },
  {
   "title": "p99 ACK latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ledger_stream_ack_seconds_bucket{outcome=\"ok\"}[1m])) by (le, stream, operation, mode))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "End to end debit latency over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (rate(ledger_debit_latency_seconds_bucket[30s]))\n)",
     "legendFormat": "Duration"
    }
   ]
  },
  {
   "title": "VU's",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max_over_time(k6_vus[30s])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average consumption-to-ledger latency (30s window)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ledger_debit_latency_seconds_sum[30s]))\n/\nsum(rate(ledger_debit_latency_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Stream Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "targets": [
    {
     "expr": "sum by (stream, group) (redis_stream_group_lag)",
     "legendFormat": "{{group}} [{{stream}}]"
    }
   ]
  },
  {
   "title": "Redis Stream Pending (In Progress)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "events" } },
   "targets": [
    {
     "expr": "redis_stream_group_consumer_messages_pending",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "MQTT Events received per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(device_mqtt_messages_received_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Events processed per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(device_mqtt_messages_processed_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(container_cpu_usage_seconds_total{name!=\"\", name!~\".*_exporter.*\"}[30s])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}